version: '3.8'

services:
  mongo-geo-db:
    hostname: mongo-hello-db
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=hello_db
      - MONGO_INITDB_ROOT_USERNAME=sysadmin
      - MONGO_INITDB_ROOT_PASSWORD=sysadmin
    volumes:
      - ~/mongo-db/data:/data/db
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == db
    ports:
      - 27017:27017
    networks:
      - database_network
 volumes:
   mongo-data-dir:

 networks:
   database_network:
       external: true
    